name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Depoyu klonla
      uses: actions/checkout@v3

    - name: Python'u ayarla
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Bağımlılıkları yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: PyInstaller ile derle
      run: |
        pyinstaller --onefile pdftray.py

    - name: Derlenen dosyayı yükle
      uses: actions/upload-artifact@v3
      with:
        name: pdftray-exe
        path: dist/pdftray.exe
